NAME = mnpgo
ENABLE_LINUX = false
MAIN_FILE = debug/connect.go

PROTOBUF_DIR=../protocol/protobuf
include ../../scripts/ci/Makefile.go

# Nothing
.PHONY: docker
docker:

.PHONY: docker-publish
docker-publish:
