NAME = mnpgo
ENABLE_LINUX = false
MAIN_FILE = debug/connect.go

PROTOBUF_DIR=../protocol/protobuf
include ../../scripts/ci/Makefile.go

# Nothing
.PHONY: api-doc docker docker-unchecked docker-publish
