NAME = tf.learn
MANTIK_ROOT=./../../../
DOCKER_IMAGE_NAME=bridge.tf.train

MANTIK_ROOT=./../../../
DOCKER_FILE=$(MANTIK_ROOT)/scripts/ci/Dockerfile.python_bridge_simple

include ../../../scripts/ci/Makefile.pythonbridge
include ../../../scripts/ci/Makefile.docker_single