include:
  - project: "mq/ci-templates"
    ref: 4a19e3c4f1cd6031607fc55f3398e9aab78352ec
    file: "/templates/storage/ci.yml"

image:
  name: reg.ambrosys.de/mantik/mantikbuilder:v4
  entrypoint: [""] # Bug https://gitlab.com/gitlab-org/gitlab-runner/issues/1170


stages:
  - build
  - verify
  - publish

build:
  stage: build
  variables:
    USER_ID: "0" # Disables suid inside docker image
    CACHE_DIR: "$PWD/cache"
  script:
    - mkdir -p $CACHE_DIR
    - make build
  cache:
    key: dependency_cache
    paths:
      - cache
  artifacts:
    paths:
      # Gitlab has no wildcard globbing yet https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      - "target"
      - "*/target"
      - "*/*/target"
      - "*/*/*/target"
      - "*/*/*/*/target"
      - "*/*/*/*/*/target"
      - "public"
    expire_in: 5 hrs

validate_copyright_header:
  stage: verify
  script:
    - ./scripts/ci/copyright_header.sh validate

test:
  stage: verify
  variables:
    USER_ID: "0" # Disables suid inside docker image
    CACHE_DIR: "$PWD/cache"
  except:
    - story/250/publish_images_to_dockerhub
  script:
    - mkdir -p $CACHE_DIR
    - make test
  cache:
    key: dependency_cache
    paths:
      - cache

docker:
  stage: verify
  image: reg.ambrosys.de/mantik/mantikdockerindocker
  variables:
    CACHE_DIR: "$PWD/cache"
    BUILDSERVER: "true" # Enables some optimizations
  cache:
    key: dependency_cache
    paths:
      - cache
  services:
    - docker:dind
  script:
    - mkdir -p $CACHE_DIR
    - make docker-unchecked

docker_publish:
  stage: publish
  image: reg.ambrosys.de/mantik/mantikdockerindocker
  variables:
    CACHE_DIR: "$PWD/cache"
    BUILDSERVER: "true"
  only:
    - master
  cache:
    key: dependency_cache
    paths:
      - cache
  services:
    - docker:dind
  script:
    - mkdir -p $CACHE_DIR
    - make docker-unchecked
    - make docker-publish

dockerhub_publish:
  stage: publish
  image: reg.ambrosys.de/mantik/mantikdockerindocker
  variables:
    CACHE_DIR: "$PWD/cache"
    BUILDSERVER: "true"
    REMOTE_REPO_NAME: registry.hub.docker.com
    REMOTE_REPO_GROUP: mantikai/
    DOCKER_USERNAME: mantikbuildserver
    DOCKER_PASSWORD: "$DOCKERHUB_ACCESS_KEY"
  only:
    - tags
    - story/250/publish_images_to_dockerhub
    - variables:
      - $CI_COMMIT_REF_PROTECTED == "true"
  cache:
    key: dependency_cache
    paths:
      - cache
  services:
    - docker:dind
  script:
    - mkdir -p $CACHE_DIR
    - make docker-unchecked
    - make docker-publish

other_publish:
  stage: publish
  only:
    - master
    - tags
    - variables:
      - $CI_COMMIT_REF_PROTECTED == "true"
  cache:
    key: dependency_cache
    paths:
      - cache
  script:
    - make publish

pages:
  variables:
    GIT_STRATEGY: none
  stage: publish
  artifacts:
    paths:
      - public
  script:
    - echo "Uploading pages"
  only:
    - master
