NAME=select_bridge
DOCKER_IMAGE_NAME=bridge.select
DOCKER_FILE=../../scripts/ci/Dockerfile.go_bridge_simple
DOCKER_EXTRA_ARGS=--build-arg input_executable=target/select_bridge_linux
include ../../scripts/ci/Makefile.go
include ../../scripts/ci/Makefile.docker_single

