NAME=mantik
PROTOBUF_DIR=../engine/src/main/protobuf
include ../scripts/ci/Makefile.go

GO_PATH ?= $(HOME)/go


.PHONY: docker
docker:

.PHONY: docker-unchecked
docker-unchecked:

.PHONY: docker-publish
docker-publish: