NAME=csv_bridge
DOCKER_IMAGE_NAME=bridge.csv
DOCKER_FILE=../../scripts/ci/Dockerfile.go_bridge_simple
DOCKER_EXTRA_ARGS=--build-arg input_executable=target/csv_bridge_linux
include ../../scripts/ci/Makefile.go
include ../../scripts/ci/Makefile.docker_single
