# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from mantik.protobuf.engine import graph_executor_pb2 as mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2


class GraphExecutorServiceStub(object):
  """Responsible for evaluating the value of graph objects. 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FetchDataSet = channel.unary_unary(
        '/ai.mantik.engine.protos.GraphExecutorService/FetchDataSet',
        request_serializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.FetchItemRequest.SerializeToString,
        response_deserializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.FetchItemResponse.FromString,
        )
    self.SaveItem = channel.unary_unary(
        '/ai.mantik.engine.protos.GraphExecutorService/SaveItem',
        request_serializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.SaveItemRequest.SerializeToString,
        response_deserializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.SaveItemResponse.FromString,
        )


class GraphExecutorServiceServicer(object):
  """Responsible for evaluating the value of graph objects. 
  """

  def FetchDataSet(self, request, context):
    """* Evaluates and fetches the content of a dataset. 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveItem(self, request, context):
    """* Evaluates and saves an item to the repository. 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GraphExecutorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FetchDataSet': grpc.unary_unary_rpc_method_handler(
          servicer.FetchDataSet,
          request_deserializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.FetchItemRequest.FromString,
          response_serializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.FetchItemResponse.SerializeToString,
      ),
      'SaveItem': grpc.unary_unary_rpc_method_handler(
          servicer.SaveItem,
          request_deserializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.SaveItemRequest.FromString,
          response_serializer=mantik_dot_protobuf_dot_engine_dot_graph__executor__pb2.SaveItemResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ai.mantik.engine.protos.GraphExecutorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
