# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mantik/engine/ds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mantik/engine/ds.proto',
  package='ai.mantik.engine.protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16mantik/engine/ds.proto\x12\x17\x61i.mantik.engine.protos\"\x18\n\x08\x44\x61taType\x12\x0c\n\x04json\x18\x01 \x01(\t\"\x8a\x01\n\x06\x42undle\x12\x34\n\tdata_type\x18\x01 \x01(\x0b\x32!.ai.mantik.engine.protos.DataType\x12\x39\n\x08\x65ncoding\x18\x02 \x01(\x0e\x32\'.ai.mantik.engine.protos.BundleEncoding\x12\x0f\n\x07\x65ncoded\x18\x03 \x01(\x0c*P\n\x0e\x42undleEncoding\x12\x14\n\x10\x45NCODING_UNKNOWN\x10\x00\x12\x15\n\x11\x45NCODING_MSG_PACK\x10\x01\x12\x11\n\rENCODING_JSON\x10\x02\x62\x06proto3')
)

_BUNDLEENCODING = _descriptor.EnumDescriptor(
  name='BundleEncoding',
  full_name='ai.mantik.engine.protos.BundleEncoding',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENCODING_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENCODING_MSG_PACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENCODING_JSON', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=218,
  serialized_end=298,
)
_sym_db.RegisterEnumDescriptor(_BUNDLEENCODING)

BundleEncoding = enum_type_wrapper.EnumTypeWrapper(_BUNDLEENCODING)
ENCODING_UNKNOWN = 0
ENCODING_MSG_PACK = 1
ENCODING_JSON = 2



_DATATYPE = _descriptor.Descriptor(
  name='DataType',
  full_name='ai.mantik.engine.protos.DataType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='ai.mantik.engine.protos.DataType.json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=75,
)


_BUNDLE = _descriptor.Descriptor(
  name='Bundle',
  full_name='ai.mantik.engine.protos.Bundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='ai.mantik.engine.protos.Bundle.data_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='ai.mantik.engine.protos.Bundle.encoding', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoded', full_name='ai.mantik.engine.protos.Bundle.encoded', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=216,
)

_BUNDLE.fields_by_name['data_type'].message_type = _DATATYPE
_BUNDLE.fields_by_name['encoding'].enum_type = _BUNDLEENCODING
DESCRIPTOR.message_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.message_types_by_name['Bundle'] = _BUNDLE
DESCRIPTOR.enum_types_by_name['BundleEncoding'] = _BUNDLEENCODING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataType = _reflection.GeneratedProtocolMessageType('DataType', (_message.Message,), dict(
  DESCRIPTOR = _DATATYPE,
  __module__ = 'mantik.engine.ds_pb2'
  # @@protoc_insertion_point(class_scope:ai.mantik.engine.protos.DataType)
  ))
_sym_db.RegisterMessage(DataType)

Bundle = _reflection.GeneratedProtocolMessageType('Bundle', (_message.Message,), dict(
  DESCRIPTOR = _BUNDLE,
  __module__ = 'mantik.engine.ds_pb2'
  # @@protoc_insertion_point(class_scope:ai.mantik.engine.protos.Bundle)
  ))
_sym_db.RegisterMessage(Bundle)


# @@protoc_insertion_point(module_scope)
