# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import remote_registry_pb2 as mantik_dot_engine_dot_remote__registry__pb2


class RemoteRegistryServiceStub(object):
    """Service for talking to a remote mantik service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullArtifact = channel.unary_unary(
                '/ai.mantik.engine.protos.RemoteRegistryService/PullArtifact',
                request_serializer=mantik_dot_engine_dot_remote__registry__pb2.PullArtifactRequest.SerializeToString,
                response_deserializer=mantik_dot_engine_dot_remote__registry__pb2.PullArtifactResponse.FromString,
                )
        self.PushArtifact = channel.unary_unary(
                '/ai.mantik.engine.protos.RemoteRegistryService/PushArtifact',
                request_serializer=mantik_dot_engine_dot_remote__registry__pb2.PushArtifactRequest.SerializeToString,
                response_deserializer=mantik_dot_engine_dot_remote__registry__pb2.PushArtifactResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/ai.mantik.engine.protos.RemoteRegistryService/Login',
                request_serializer=mantik_dot_engine_dot_remote__registry__pb2.LoginRequest.SerializeToString,
                response_deserializer=mantik_dot_engine_dot_remote__registry__pb2.LoginResponse.FromString,
                )


class RemoteRegistryServiceServicer(object):
    """Service for talking to a remote mantik service
    """

    def PullArtifact(self, request, context):
        """Pulls an artifact from Remote registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushArtifact(self, request, context):
        """Pushes an artifact to the remote registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Execute a login request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PullArtifact,
                    request_deserializer=mantik_dot_engine_dot_remote__registry__pb2.PullArtifactRequest.FromString,
                    response_serializer=mantik_dot_engine_dot_remote__registry__pb2.PullArtifactResponse.SerializeToString,
            ),
            'PushArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PushArtifact,
                    request_deserializer=mantik_dot_engine_dot_remote__registry__pb2.PushArtifactRequest.FromString,
                    response_serializer=mantik_dot_engine_dot_remote__registry__pb2.PushArtifactResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=mantik_dot_engine_dot_remote__registry__pb2.LoginRequest.FromString,
                    response_serializer=mantik_dot_engine_dot_remote__registry__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.mantik.engine.protos.RemoteRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteRegistryService(object):
    """Service for talking to a remote mantik service
    """

    @staticmethod
    def PullArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.mantik.engine.protos.RemoteRegistryService/PullArtifact',
            mantik_dot_engine_dot_remote__registry__pb2.PullArtifactRequest.SerializeToString,
            mantik_dot_engine_dot_remote__registry__pb2.PullArtifactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PushArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.mantik.engine.protos.RemoteRegistryService/PushArtifact',
            mantik_dot_engine_dot_remote__registry__pb2.PushArtifactRequest.SerializeToString,
            mantik_dot_engine_dot_remote__registry__pb2.PushArtifactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.mantik.engine.protos.RemoteRegistryService/Login',
            mantik_dot_engine_dot_remote__registry__pb2.LoginRequest.SerializeToString,
            mantik_dot_engine_dot_remote__registry__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
