# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import sessions_pb2 as mantik_dot_engine_dot_sessions__pb2


class SessionServiceStub(object):
    """* Service for session handling. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/ai.mantik.engine.protos.SessionService/CreateSession',
                request_serializer=mantik_dot_engine_dot_sessions__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=mantik_dot_engine_dot_sessions__pb2.CreateSessionResponse.FromString,
                )
        self.CloseSession = channel.unary_unary(
                '/ai.mantik.engine.protos.SessionService/CloseSession',
                request_serializer=mantik_dot_engine_dot_sessions__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=mantik_dot_engine_dot_sessions__pb2.CloseSessionResponse.FromString,
                )


class SessionServiceServicer(object):
    """* Service for session handling. 
    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=mantik_dot_engine_dot_sessions__pb2.CreateSessionRequest.FromString,
                    response_serializer=mantik_dot_engine_dot_sessions__pb2.CreateSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=mantik_dot_engine_dot_sessions__pb2.CloseSessionRequest.FromString,
                    response_serializer=mantik_dot_engine_dot_sessions__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.mantik.engine.protos.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """* Service for session handling. 
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.mantik.engine.protos.SessionService/CreateSession',
            mantik_dot_engine_dot_sessions__pb2.CreateSessionRequest.SerializeToString,
            mantik_dot_engine_dot_sessions__pb2.CreateSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.mantik.engine.protos.SessionService/CloseSession',
            mantik_dot_engine_dot_sessions__pb2.CloseSessionRequest.SerializeToString,
            mantik_dot_engine_dot_sessions__pb2.CloseSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
