NAME = go_shared
ENABLE_LINUX = false
MAIN_FILE = lib.go
PROTOBUF_DIR=../bridge/protocol/protobuf

include ../scripts/ci/Makefile.go

# Nothing
.PHONY: docker
docker:

.PHONY: docker-publish
docker-publish: