NAME=mantik_dev
MANTIK_ROOT=./../
DOCKER_IMAGE_NAME=mantik_dev
DOCKER_FILE=$(MANTIK_ROOT)/scripts/ci/Dockerfile.mantik_dev_image
include ./../scripts/ci/Makefile.docker_single
include ./../scripts/ci/Makefile.pythonbridge

target/copy_shared.make: $(shell find $(MANTIK_ROOT)/python_sdk -name "*.py")
	mkdir -p target/python_sdk

	cp $(MANTIK_ROOT)/python_sdk/pyproject.toml target/python_sdk
	cp $(MANTIK_ROOT)/python_sdk/poetry.lock target/python_sdk
	cp -v -r $(MANTIK_ROOT)/python_sdk/mantik target/python_sdk
	cp -v -r $(MANTIK_ROOT)/mnp/mnppython target/

	#sed -i 's/".*python_sdk"/"\.\/python_sdk"/' target/poetry.lock target/pyproject.toml
	#sed -i 's/".*mnppython"/"\.\/mnppython"/' python_sdk/poetry.lock python_sdk/pyproject.toml
	sed -i 's/".*mnppython"/"\.\/..\/mnppython"/' target/python_sdk/poetry.lock target/python_sdk/pyproject.toml

	touch $@
